name: Update GitHub Profile

on:
  # schedule:
    # 毎日 00:00 UTC（日本時間 09:00）に実行
    # - cron: "0 0 * * *"
  workflow_dispatch: # 手動実行も可能

permissions:
  contents: write # README.md を更新するために必要

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub Profile
        uses: watsumi/update-gh-profile@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          exclude_forks: "true"
          exclude_languages: "HTML,CSS,JSON"
